### ISSUE TITLE
[v3] Why every file between edited file and root is updated?

### ISSUE THREAD

**Issue by pilaas** [gaearon/react-hot-boilerplate#104]
In RHL@1 the console used to log:

```
[HMR] Updated modules:
[HMR] - <module_id>
```
Currently, in RHL@3 the console logs whole path between edited file and the root component.
Is it correct with RHL philosophy that only the updated module should be replaced? Why is there such change?

![screen shot 2016-12-01 at 22 40 46](https://cloud.githubusercontent.com/assets/80428/20813897/c548b49e-b817-11e6-948f-763e169f4f15.png)

Counter imports Button and Button imports Link, it's extended version of 'next' branch.
It can lead to the situation when the whole console is polluted by number of module names which has been changed (even if only one changed).

**Comment by calesce** [comment]
`WebpackDevServer` has a [`clientLogLevel` option](https://webpack.js.org/configuration/dev-server/#devserver-clientloglevel) that's supposed to quiet that output, but it hasn't worked very well in my experience.

If you use `webpack-hot-middleware`, you can reliably quiet output when adding it to the Webpack config's `entry` array, see [here](https://github.com/calesce/tab-editor/blob/8a7c427b1efc56398ed473e9bf2c9e232b47daf5/webpack.config.dev.js#L8).

We're probably not going to disable this output in this boilerplate, but instead point people to Webpack's docs.
