### ISSUE TITLE
How can i get static files?

### ISSUE THREAD

**Issue by Infonautica** [gaearon/react-hot-boilerplate#105]
### Description
Have a trouble with static files
`entry: [
    'webpack-hot-middleware/client',
    './src/app'
],
output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
}`

React applications is works fine, but without css and other static files. I put them in "dist" folder, but still cant get them, so:
`<script src="/static/bundle.js"></script>` // Works fine
`<link href="/static/css/main.min.css" rel="stylesheet">` // Cant get

### Environment
React Hot Loader version: 1.3.1
1. `node -v`: 4.4.7
2. `npm -v`: 3.10.5
1. Operating system: Windows
2. Browser and version: Chrome

**Comment by arixse** [comment]
add 'build' scripts config in package.json ,then run 'npm run build'
```javascript
scripts:{
"build":"webpack --progress --profile --colors"
}
```

**Comment by JasoonS** [comment]
I'm having the exact same issue.

@arixse I feel you didn't quite understand the question. We would like to serve static files with the server during the development process.

**Comment by JasoonS** [comment]
The solution is detailed [here](https://expressjs.com/en/starter/static-files.html).

For you adding `app.use('/static', express.static('dist'))` somewhere to your server.js file should do the trick. :)

**Comment by calesce** [comment]
Yep, see above for Express. For `WebpackDevServer`, use [the `contentBase` option](https://webpack.js.org/configuration/dev-server/#devserver-contentbase)
