### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by nicelj** [gaearon/react-hot-boilerplate#106]
can not work.I just clone the code and run it without changing anything.

**Comment by pilaas** [comment]
Works for me. I've pulled and launched master branch successfully. What do you mean by 'not work' ?

**Comment by nicelj** [comment]
well , i did the same thing with you,and i have upgraded my npm just now.Now,i find it cant work in webstorm but can work in notepad++.i dont know why..

**Comment by pilaas** [comment]
Then I don't think it's problem with this repo.

**Comment by mikelambert** [comment]
Webstorm uses "safe writes", which break the change-detection logic. From another thread:
> Disable "safe write" in Webstorm preferences - Appearance & Behavior / System Settings and on this page uncheck: Use "safe write""

**Comment by joetidee** [comment]
OMG - I have been tearing my hair our with the WEbpack config for 2 days and it has been WebStorm all along! Arrrghhh! (and thanks :)).

**Comment by calesce** [comment]
Yeah this looks like a Webstorm issue. Might be worth mentioning in the README.

**Comment by calesce** [comment]
the issue's now documented in the README. thanks!
