### ISSUE TITLE
Should react-hot-loader be loaded on production builds?

### ISSUE THREAD

**Issue by mschipperheyn** [gaearon/react-hot-boilerplate#107]
All the examples i see for react-hot-loader include the
    
     import { AppContainer }  from 'react-hot-loader'; 

However, it doesn't make a lot of sense to include react-hot-loader on a production build. Shouldn't this be separated out to dev build only and as such be reflected in this boiletplate?

**Comment by pilaas** [comment]
If the module.hot is false or `NODE_ENV` === 'production' then the AppContainer will simply pass all children and props to inner component. See: https://github.com/gaearon/react-hot-loader/blob/v3.0.0-beta.6/src/AppContainer.js

**Comment by calesce** [comment]
Yes, we plan on adding a production build (tracked in #63), but only via `NODE_ENV`, not separate code paths.
