### ISSUE TITLE
sourcemap issue

### ISSUE THREAD

**Issue by foisonocean** [gaearon/react-hot-boilerplate#108]
### Use `devtool: 'source-map'` will fix it.

**Comment by calesce** [comment]
I agree it's a problem, unfortunately there's a tradeoff for each type of `devtool`. The [documentation](https://webpack.js.org/configuration/devtool/) sums up the tradeoffs.

`inline-source-map`, which includes full source maps in the same bundle file, will be the default when we merge #111. It is slower, but much more usable and probably better for this boilerplate.
