### ISSUE TITLE
Can't get the boilerplate code to npm-start

### ISSUE THREAD

**Issue by VasilyShelkov** [gaearon/react-hot-boilerplate#11]
Hi, 

wasn't sure where else to post, but I tried to make a hello world app with hot-module-loader, which wasn't working and then just decided to check this out of the repository to see whether it was my code that was the problem.

npm install fine, then npm start and I get this error. I get this same error in my hello world app: 

C:\Users\Vasia\WebstormProjects\react-hot-boilerplate>npm install

C:\Users\Vasia\WebstormProjects\react-hot-boilerplate>npm start

> react-hot-boilerplate@1.0.0 start C:\Users\Vasia\WebstormProjects\react-hot-boilerplate
> node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'tapable'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Vasia\WebstormProjects\react-hot-boilerplate\node_modules\webpack\lib\Compiler.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! react-hot-boilerplate@1.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the react-hot-boilerplate@1.0.0 start script.
npm ERR! This is most likely a problem with the react-hot-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-hot-boilerplate
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd C:\Users\Vasia\WebstormProjects\react-hot-boilerplate
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Vasia\WebstormProjects\react-hot-boilerplate\npm-debug.log
npm ERR! not ok code 0

Any help is much appreciated.

PS I'm running windows 8.1 but looking at your closed issues that shouldn't be a problem

Thanks,
Vasia

**Comment by gaearon** [comment]
Any change `npm install` hasn't completed successfully?

**Comment by VasilyShelkov** [comment]
I'm assuming you meant 'chance' and it doesn't look like it : 

C:\Users\Vasia\WebstormProjects\react-hot-boilerplate>npm install

C:\Users\Vasia\WebstormProjects\react-hot-boilerplate>npm start

I don't get any messages after npm install. If that's normal :S

**Comment by VasilyShelkov** [comment]
I don't think it should make a difference, but I'm using webstorm 9

**Comment by gaearon** [comment]
>I don't get any messages after npm install. If that's normal :S

Normally `npm install` should print installed packages. Can you verify `node_modules/webpack/node_modules/tapable` exists?

You can try deleting `node_modules` and running `npm install` again.

**Comment by VasilyShelkov** [comment]
will try doing that, sorry haven't had a chance to yet.

**Comment by gaearon** [comment]
Closing, as it seems to be a local NPM issue.
