### ISSUE TITLE
How to contribute a TypeScript boilerplate for react-hot-loader

### ISSUE THREAD

**Issue by mutsys** [gaearon/react-hot-boilerplate#110]
I recently have been able to get a project working using React Hot Loader 3 with TypeScript 2.2 and Webpack 2 and I would like to contribute a boilerplate example. What would be the preferred method of sharing this with the community? As a branch of `react-hot-boilerplate`? As a fork available elsewhere?

**Comment by calesce** [comment]
A separate repository is probably best. Also see https://github.com/sormy/skeleton-react-typescript-hot-v3
