### ISSUE TITLE
'react-hot-loader/babel' seems useless in `.babelrc`

### ISSUE THREAD

**Issue by SidKwok** [gaearon/react-hot-boilerplate#115]
If I remove `"plugins": ["react-hot-loader/babel"]`, the HMR also run correctly.

Will the plugin be added automatically?

I want to use babel's env to remove this plugin in my production, so will it be removed from my production?

react-hot-loader 3.0.0@beta.6

**Comment by calesce** [comment]
HMR runs correctly but the point of the Babel plugin is to prevent stateful React components from unmounting on HMR updates, so they retain their state.
