### ISSUE TITLE
not working if I made some changes in functions

### ISSUE THREAD

**Issue by xiaojingzhao091** [gaearon/react-hot-boilerplate#138]
Here is an example
```
export default class App extends Component {
  render() {
    return (
      <h1 >Hello, world.</h1>
    );
  }
}
```

if I bind an onClick functions for this "Hello word"
```
import React, { Component } from 'react';

export default class App extends Component {
  onClick = () => {
    console.log('2222222222')
  }
  render() {
    return (
      <h1 onClick={this.onClick} >Hello, world.</h1>
    );
  }
}
```

The rebuilding occurred. However, if I click "Hello world", nothing consoled  in console panel.

It seems hot-loader only hot replace UI relevant stuff. I wonder if I could hot load function?

**Comment by theKashey** [comment]
Duplicate https://github.com/gaearon/react-hot-loader/issues/903
