### ISSUE TITLE
Not reloading after save

### ISSUE THREAD

**Issue by eiktyrner** [gaearon/react-hot-boilerplate#14]
This looks like a really cool feature but I can't seem to get it to trigger no matter what. I've tried the other starter kits as well but no luck there either. For any changes to take effect I need to run npm start again each time.

    Arch Linux 64 bit
    node v0.10.36
    npm 2.3.0

Browser console in Chromium 40.0.2214.93 (64-bit) 

    [HMR] Waiting for update signal from WDS...
    [WDS] Hot Module Replacement enabled.

Output from running npm start. 

    > node server.js    
    Listening at localhost:3000
    Hash: 42936a5ff1b93df92458
    Version: webpack 1.5.3
    Time: 922ms
        Asset    Size  Chunks             Chunk Names
    bundle.js  780270       0  [emitted]  main
    chunk    {0} bundle.js (main) 680118 [rendered]

    * MY EDIT BELOW
    [0-165] built...etc

    webpack: bundle is now VALID.

I change the text in the \<h1> in scripts/app.js but nothing happens in the browser. No more output or any error messages.

Please advice on how I can debug this.

**Comment by gaearon** [comment]
Here's what I see in Network tab:

Before saving

![screen shot 2015-02-16 at 15 18 52](https://cloud.githubusercontent.com/assets/810438/6212026/a15915ee-b5f1-11e4-80f9-1aa4b963a1ad.png)

After saving

![screen shot 2015-02-16 at 15 19 05](https://cloud.githubusercontent.com/assets/810438/6212027/a788ef0c-b5f1-11e4-90fe-f942cd884ec5.png)


Do you see any of these?

**Comment by eiktyrner** [comment]
I get the first ones but nothing after saving. It will recognize the server going down though when I ctrl+c it. So it has some kind of connection back to the server. It just doesn't catch any updates.

**Comment by gaearon** [comment]
Please file this in [Webpack repo](https://github.com/webpack/webpack). This has to be some kind of connection problem but I don't know how to debug it.

**Comment by eiktyrner** [comment]
Will do, thanks!

**Comment by gaearon** [comment]
+ let us know if you find a solution! I'm collecting those in https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md
