### ISSUE TITLE
Can't figure out the ES6 error

### ISSUE THREAD

**Issue by jcw** [gaearon/react-hot-boilerplate#16]
With my apologies for posting here - I'm trying to dip my toes into the ES6 + React + hot-reload waters, and this project really helped with getting things going. Everything works as described.

But now I'm trying to extend the example:

```
import React from 'react';

class OnOff extends React.Component {
  render() {
    return (
      <input type="checkbox" id="onoff" />
      <label for="onoff">Enable</label>
    );
  }
}

export default class App extends React.Component {
  render() {
    return (
      <h1>Hello, world.</h1>
      <OnOff />
    );
  }
}
```

It leads to this error message:

```
   5 |     return (
   6 |       <input type="checkbox" id="onoff" />
>  7 |       <label for="onoff">Enable</label>
     |              ^
   8 |     );
   9 |   }
  10 | }
```

Changing things around moves the error in ways I really don't understand at all. It almost looks like JSX is not enabled, but that would lead to a lot more errors, and your minimal demo wouldn't even run!

_I must be overlooking something totally trivial..._  
-jcw

**Comment by jcw** [comment]
Aha, noob territory, clearly - using a different starter project, I got the message "Uncaught Error: Parse Error: Line 26: Adjacent JSX elements must be wrapped in an enclosing tag". That explains everything.

But now the question is: why did this error didn't show up here?

-jcw

**Comment by gaearon** [comment]
I think this was because React's JSX tool gives a better message than Babel in this case.
I'll file an issue with Babel.

**Comment by gaearon** [comment]
Filed as https://github.com/babel/babel/issues/1008, you can track it there!

**Comment by jcw** [comment]
FWIW, I'm getting much better error messages with React's JSX tool all around, not just for this case.

**Comment by gaearon** [comment]
Acorn has some catching up to do. I'm sure it'll improve if you keep filing them :-)
