### ISSUE TITLE
hot module is 404ing 

### ISSUE THREAD

**Issue by marr** [gaearon/react-hot-boilerplate#17]
Hi Dan,
Any clue what could be going on here? http://cl.ly/image/0E0l1w3C402N

I tried pulling out the config into a project im trying to get HMR working on, so its not specific to this repo, but I'm not sure where else to post. [Here is the repo](https://github.com/bitwise/status), and `node server.js` should start up and behave as shown above. Basically the module name doesnt appear to be updated in console so its still looking for the old module. Also I notice the compilation step happens twice.

Thanks,
Dave

**Comment by marr** [comment]
Appears this might be normal, according to https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#the-following-modules-couldnt-be-hot-updated-they-would-need-a-full-reload

I am just confused because I do see the reload actually working but it still 404s.

**Comment by gaearon** [comment]
I think older versions of WebpackDevServer used 404 as status code for “no updates” but a lot of people were confused by this, so it was changed. You're using WDS 1.2.4 but the latest version is 1.7.0. Upgrading WDS will solve your issue.
