### ISSUE TITLE
Why is strict mode disallowed in .eslintrc?

### ISSUE THREAD

**Issue by kmoe** [gaearon/react-hot-boilerplate#30]
Strict mode is disallowed using the ESLint "never" setting:
https://github.com/gaearon/react-hot-boilerplate/blob/master/.eslintrc#L13

Why is this?

**Comment by gaearon** [comment]
We're using ES6 modules and they imply `use strict` anyway by the spec.
Babel's output generates `'use strict'` automatically so there's no need to add it manually.

(As far as I know.)

**Comment by kmoe** [comment]
Thanks! Found this which explains it further http://babeljs.io/docs/advanced/transformers/other/strict/

Closing as resolved.
