### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by windgaucho** [gaearon/react-hot-boilerplate#47]
I just download the repository, run npm install and all is good, but when I try to run with npm start I am getting an error.

This is the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-hot-boilerplate@1.0.0
6 info start react-hot-boilerplate@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info react-hot-boilerplate@1.0.0 Failed to exec start script
9 verbose stack Error: react-hot-boilerplate@1.0.0 start: `node server.js`
9 verbose stack Exit status 3221225501
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-hot-boilerplate@1.0.0
11 verbose cwd C:\Luis\Desarrollo\React\react-hot-boilerplate-master
12 error Windows_NT 6.1.7600
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.3
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error react-hot-boilerplate@1.0.0 start: `node server.js`
17 error Exit status 3221225501
18 error Failed at the react-hot-boilerplate@1.0.0 start script 'node server.js'.
18 error This is most likely a problem with the react-hot-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls react-hot-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Any ideas? Thanks

**Comment by anyexinglu** [comment]
Having the same problem @windgaucho

**Comment by licongmu** [comment]
me too

**Comment by scheijan** [comment]
Me too, but I find several people having the same issue with different packages. I think this is rather a "npm on windows" problem than one with react-hot-boilerplate...

**Comment by gaearon** [comment]
Indeed this is not something we can fix on our side. Either a Node.js or an npm problem.
