### ISSUE TITLE
Build and package to production aka another computer

### ISSUE THREAD

**Issue by ibiza240** [gaearon/react-hot-boilerplate#48]
Hi!

I'm very new at `npm`, `node`, `react` and all of this - but I managed to use with great ease your react-hot-boilerplate configuration script! :+1: 

Now that I have a site I like when I run `npm start`, what would be the easiest/best way to add a production build in the configuration? I would like to have a little folder build with all the final html and js files in it when I build for prod, is that what I should expect?

Thank you very much for your work and time!

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/react-hot-boilerplate/issues/13.
