### ISSUE TITLE
Trouble embedding it in Flask app

### ISSUE THREAD

**Issue by aitchnyu** [gaearon/react-hot-boilerplate#59]
I want the compiled app within my Flask (Python web framework) app which serves at port 5000. So I embedded the bundle within Flask template like:

`<script` src="http://localhost:3000/static/bundle.js"></script>`

I then load my app at localhost:5000 and it loads fine, all but the last request are successful. The last request is triggered by a code change and it fails since the request goes to port 5000. 

```
Request URL:http://localhost:5000/

Request URL:http://localhost:3000/static/bundle.js

Request URL:http://localhost:3000/sockjs-node/info?t=1460205226170

Request URL:ws://localhost:3000/sockjs-node/388/o2owupos/websocket

Request` URL:http://localhost:5000/static/3d78a8f83264d3f603be.hot-update.json
```

Webpack generates following when I edit code:
```
Hash: be0f4b289250fb4f2536
Version: webpack 1.12.14
Time: 309ms
                               Asset      Size  Chunks             Chunk Names
                           bundle.js   1.01 MB       0  [emitted]  main
0.3d78a8f83264d3f603be.hot-update.js   3.73 kB       0  [emitted]  main
3d78a8f83264d3f603be.hot-update.json  36 bytes          [emitted]  
chunk    {0} bundle.js, 0.3d78a8f83264d3f603be.hot-update.js (main) 875 kB [rendered]
```
 
Please fix the request webpack makes to `.hot-update.json` too. All other requests are correct.

Sorry if this was the wrong place for raising this concern. I asked here as most people copy this repo for their react boilerplates. I look forward to be using your awesome work!

**Comment by gaearon** [comment]
Please put `publicPath: 'http://localhost:3000/static/'` in your Webpack config.
