### ISSUE TITLE
Add production build

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-hot-boilerplate#63]
We should have one. It’s not very obvious how to do it. 😉

**Comment by jlippold** [comment]
For those of us using the current version, how do we build since `npm build` isnt here yet?

**Comment by danmartinez101** [comment]
Check out this comment for a basic answer: https://github.com/gaearon/react-hot-boilerplate/issues/13#issuecomment-73414559

You might also be interested in this PR which includes an `npm run build`: https://github.com/gaearon/react-hot-boilerplate/pull/81

**Comment by jlippold** [comment]
thanks :)

**Comment by calesce** [comment]
closed via #118
