### ISSUE TITLE
Add support for mocha-loader for testing?

### ISSUE THREAD

**Issue by hanfeisun** [gaearon/react-hot-boilerplate#67]
Will this boilerplate add support for testing?

**Comment by adam-beck** [comment]
With so many other boilerplates out there, I personally don't think we should be adding to this one. Keeping with the project's description (emphasis mine):

> The minimal dev environment to **enable live-editing React components**

This one is easier to understand because there is no "clutter". But, this is just my opinion.

**Comment by calesce** [comment]
Agreed with @adam-beck.
