### ISSUE TITLE
Nothing happens when I edit App.js

### ISSUE THREAD

**Issue by karvar** [gaearon/react-hot-boilerplate#87]
I cloned a clean repo of this boilerplate and am able to build the "Hello World" app. I am getting a log in the console that says “[WDS] Hot Module Replacement enabled” but editting my App.js does not trigger a page reload. I looked at [this part of the troubleshooting guide](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#i-see-wds-hot-module-replacement-enabled-but-nothing-happens-when-i-edit-appjs) but nothing seemed to work. I am running npm v2.15.1 and node v0.12.15 in Ubuntu 16.04.

**Comment by karvar** [comment]
![image](https://cloud.githubusercontent.com/assets/4406953/17253770/23daada0-5580-11e6-9af0-7163e3a09326.png)

**Comment by ryanrogalski** [comment]
@karvar Did you ever resolve this issue? I am having the same problem despite using this boilerplate successfully in the past.

**Comment by karvar** [comment]
Yes the issue was resolved. 

[From the react-hot-loader troubleshooting page](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md)
> Not enough watchers
> 
> Verify that if you have enough available watchers in your system. If this value is too low, the file watcher in Webpack won't recognize the changes:
> 
> cat /proc/sys/fs/inotify/max_user_watches
> Arch users, add fs.inotify.max_user_watches=524288 to /etc/sysctl.d/99-sysctl.conf and then execute sysctl --system. Ubuntu users (and possibly others): echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p.
