### ISSUE TITLE
[Proposal] Change devtool from eval to eval-source-map

### ISSUE THREAD

**Issue by canibanoglu** [gaearon/react-hot-boilerplate#89]
Hello,

I've been using this boilerplate to create toy projects to explore tools and each time I find myself fixing up the `devtool` option for webpack so that I can debug my own source code in Chrome.

I assume many people are also including the `source-map` option, mainly because most of the issues opened here with webpack configurations seem to have it set. 

I would be more than happy to create a pull request for this.

Cheers,

Can

**Comment by calesce** [comment]
We went with [`cheap-module-eval-source-map`](https://webpack.github.io/docs/configuration.html#devtool) as the best tradeoff in source-map quality and compilation time.
