### ISSUE TITLE
Bundling for production

### ISSUE THREAD

**Issue by dagumak** [gaearon/react-hot-boilerplate#90]
How can I make the bundles smaller? Between react, jQuery, and bootstrap, my builds are already huge! I tried the following configurations, but it still seems to be very big (1.2MB). Is there a recommended configuration? It might be even better to avoid bundling jQuery, bootstrap, and react together. Having the separate will let the browser download these in parallel. Thoughts?

```
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify('production')
            }
        }),
        new webpack.ProvidePlugin({
            $:      "jquery",
            jQuery: "jquery"
        }),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: { warnings: false },
            comments: false,
            sourceMap: false,
            mangle: {
                toplevel: true
            }
        })
    ]
```

**Comment by dagumak** [comment]
I found your other post, and it said to use ``devtool: 'source-map'`` and that made a huge difference! That dropped it from 1.2M to 405kb. Still kind of big, but a lot better now.

**Comment by calesce** [comment]
We're tracking this in #63, will update soon!
