### ISSUE TITLE
How to add support for immutable js?

### ISSUE THREAD

**Issue by vandervidi** [gaearon/react-hot-boilerplate#95]
When using for example Map() object from immutable.js , Chrome throws an error:

`Uncaught TypeError: Constructor Map requires 'new'`

**Comment by chrisngobanh** [comment]
You probably for to import Map from Immutable because the built-in Maps in JavaScript need to be instantiated with 'new'

`import { Map } from 'immutable'`

**Comment by calesce** [comment]
You're probably not using a supported browser. I'd recommend using [Babel](http://babeljs.io/)

**Comment by calesce** [comment]
Don't this is related to this project.
