### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by sormy** [gaearon/react-hot-boilerplate#96]
Hi.

I did TypeScript version. You could refer it if somebody needs.

https://github.com/sormy/skeleton-react-typescript-hot-v1
https://github.com/sormy/skeleton-react-typescript-hot-v3

Thank you.

**Comment by aalpgiray** [comment]
I have a question did you use react-router and a-sync routes? I could not be able to make it run. 

this is my [v1 boilerplate](https://github.com/aalpgiray/react-hot-boilerplate-ts)

I am failing to upgrade v3

**Comment by sormy** [comment]
aalpgiray: no, this is primitive sample but it works and state of react components is preserved

**Comment by calesce** [comment]
Thanks, want to make a PR to `master` and `next` adding those links?

**Comment by calesce** [comment]
If you'd still like, make a PR [here](https://github.com/gaearon/react-hot-loader/blob/master/docs/README.md#starter-kits).
