### ISSUE TITLE
Question only?

### ISSUE THREAD

**Issue by brianbier** [gaearon/react-hot-boilerplate#98]
Hey I was trying to understand how the webpack auto reload is working. 
I know your using a webpack-dev-server, but what part of your code is forcing the reload to happen when you edit a component? 

Thanks in advance. Any resources is much appreciated.

**Comment by dawsonbotsford** [comment]
@brianbier The parsed jsx is served using `WebPackDevServer` [here](https://github.com/gaearon/react-hot-boilerplate/blob/master/server.js#L5). This means that the server is able to both have access to your filesystem (listen for file changes), and refresh the browser.

If you want to read more about that "refresh the browser" part above, take a look at the [WebPack Docs Explanation](https://webpack.github.io/docs/hot-module-replacement-with-webpack.html#how-does-it-work)

**Comment by calesce** [comment]
thanks for the answer @dawsonbotsford, I recommend reading Webpack Docs and [Dan's blog post on approaches to hot reloading in React](https://medium.com/@dan_abramov/hot-reloading-in-react-1140438583bf#.9xt9iwm3v).
